import type { DummyUser } from '#/types/dummyUsers'

export const dummyUsers = [
  {
    id: 1,
    firstName: 'Emily',
    lastName: 'Johnson',
    maidenName: 'Tucks',
    role: 'admin' as DummyUser['role'],
    gender: 'female' as DummyUser['gender'],
    weight: 63,
    university: 'Harvard',
    email: 'emily.johnson@x.dummyjson.com',
    phone: '+81 965-431-3024',
    username: 'emilys',
    birthDate: '1996-5-30',
    image: 'https://dummyjson.com/icon/emilys/128',
    address: {
      address: '626 Main Street',
      city: 'Phoenix',
      state: 'Mississippi',
      stateCode: 'MS',
      postalCode: '29112',
      coordinates: {
        lat: -77.16213,
        lng: -92.084824,
      },
      country: 'United States',
    },
    company: {
      department: 'Engineering',
      name: 'Dooley, Kozey and Cronin',
      title: 'Sales Manager',
      address: {
        address: '263 Tenth Street',
        city: 'San Francisco',
        state: 'Wisconsin',
        stateCode: 'WI',
        postalCode: '37657',
        coordinates: {
          lat: 71.814525,
          lng: -161.150263,
        },
        country: 'United States',
      },
    },
  },
  {
    id: 8,
    firstName: 'Ava',
    lastName: 'Taylor',
    maidenName: 'Gyn',
    role: 'user' as DummyUser['role'],
    gender: 'female' as DummyUser['gender'],
    weight: 59,
    university: 'MIT',
    email: 'ava.taylor@x.dummyjson.com',
    phone: '+1 458-853-7877',
    username: 'avat',
    birthDate: '1997-8-25',
    image: 'https://dummyjson.com/icon/avat/128',
    address: {
      address: '1197 First Street',
      city: 'Fort Worth',
      state: 'Rhode Island',
      stateCode: 'RI',
      postalCode: '24771',
      coordinates: {
        lat: -81.194833,
        lng: -87.948158,
      },
      country: 'United States',
    },
    company: {
      department: 'Marketing',
      name: 'Nikolaus Inc',
      title: 'Chief Executive Officer',
      address: {
        address: '930 Lincoln Street',
        city: 'Austin',
        state: 'Colorado',
        stateCode: 'CO',
        postalCode: '47592',
        coordinates: {
          lat: 87.970083,
          lng: -42.769351,
        },
        country: 'United States',
      },
    },
  },
]
