export const icons = {
  User: 'user',
  UserPlus: 'user-plus',
  UsersRound: 'users-round',
  Grid2x2Check: 'grid-2x2-check',
  Hamburger: 'hamburger',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
  CircleCheck: 'circle-check',
  CircleX: 'circle-x',
  Earth: 'earth',
  ShieldPlus: 'shield-plus',
  EllipsisVertical: 'ellipsis-vertical',
  Eye: 'eye',
  SquarePen: 'square-pen',
  UserPen: 'user-pen',
  Trash2: 'trash-2',
  ArrowUpDown: 'arrow-up-down',
  ArrowUp: 'arrow-up',
  ArrowDown: 'arrow-down',
  Info: 'info',
  Building2: 'building-2',
  ChartColumn: 'chart-column',
  CircleUser: 'circle-user',
  LogOut: 'log-out',
} as const

export type IconName = (typeof icons)[keyof typeof icons]
