/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAboutRouteImport } from './routes/dashboard/about'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardDepartmentsIndexRouteImport } from './routes/dashboard/departments/index'
import { Route as DashboardUsersNewRouteImport } from './routes/dashboard/users/new'
import { Route as DashboardUsersUserIdIndexRouteImport } from './routes/dashboard/users/$userId/index'
import { Route as DashboardDepartmentsDepartmentIdIndexRouteImport } from './routes/dashboard/departments/$departmentId/index'
import { Route as DashboardUsersUserIdEditRouteImport } from './routes/dashboard/users/$userId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepartmentsIndexRoute =
  DashboardDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersNewRoute = DashboardUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersUserIdIndexRoute =
  DashboardUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDepartmentsDepartmentIdIndexRoute =
  DashboardDepartmentsDepartmentIdIndexRouteImport.update({
    id: '/departments/$departmentId/',
    path: '/departments/$departmentId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersUserIdEditRoute =
  DashboardUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
  '/dashboard/departments/$departmentId/': typeof DashboardDepartmentsDepartmentIdIndexRoute
  '/dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
  '/dashboard/departments/$departmentId': typeof DashboardDepartmentsDepartmentIdIndexRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/users/new': typeof DashboardUsersNewRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
  '/dashboard/departments/$departmentId/': typeof DashboardDepartmentsDepartmentIdIndexRoute
  '/dashboard/users/$userId/': typeof DashboardUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/dashboard/about'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/users/new'
    | '/dashboard/departments/'
    | '/dashboard/users/'
    | '/dashboard/users/$userId/edit'
    | '/dashboard/departments/$departmentId/'
    | '/dashboard/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/login'
    | '/dashboard/about'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/users/new'
    | '/dashboard/departments'
    | '/dashboard/users'
    | '/dashboard/users/$userId/edit'
    | '/dashboard/departments/$departmentId'
    | '/dashboard/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/dashboard/about'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/users/new'
    | '/dashboard/departments/'
    | '/dashboard/users/'
    | '/dashboard/users/$userId/edit'
    | '/dashboard/departments/$departmentId/'
    | '/dashboard/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/departments/': {
      id: '/dashboard/departments/'
      path: '/departments'
      fullPath: '/dashboard/departments/'
      preLoaderRoute: typeof DashboardDepartmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/new': {
      id: '/dashboard/users/new'
      path: '/users/new'
      fullPath: '/dashboard/users/new'
      preLoaderRoute: typeof DashboardUsersNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$userId/': {
      id: '/dashboard/users/$userId/'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId/'
      preLoaderRoute: typeof DashboardUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/departments/$departmentId/': {
      id: '/dashboard/departments/$departmentId/'
      path: '/departments/$departmentId'
      fullPath: '/dashboard/departments/$departmentId/'
      preLoaderRoute: typeof DashboardDepartmentsDepartmentIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$userId/edit': {
      id: '/dashboard/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/dashboard/users/$userId/edit'
      preLoaderRoute: typeof DashboardUsersUserIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersNewRoute: typeof DashboardUsersNewRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersUserIdEditRoute: typeof DashboardUsersUserIdEditRoute
  DashboardDepartmentsDepartmentIdIndexRoute: typeof DashboardDepartmentsDepartmentIdIndexRoute
  DashboardUsersUserIdIndexRoute: typeof DashboardUsersUserIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersNewRoute: DashboardUsersNewRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersUserIdEditRoute: DashboardUsersUserIdEditRoute,
  DashboardDepartmentsDepartmentIdIndexRoute:
    DashboardDepartmentsDepartmentIdIndexRoute,
  DashboardUsersUserIdIndexRoute: DashboardUsersUserIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
